// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.sforce.eventbus {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
    public partial class AccountChangeEvent : global::Avro.Specific.ISpecificRecord {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AccountChangeEvent\",\"namespace\":\"com.sforce.eventbus\",\"f" +
                "ields\":[{\"name\":\"ChangeEventHeader\",\"doc\":\"Data:ComplexValueType\",\"type\":{\"type\"" +
                ":\"record\",\"name\":\"ChangeEventHeader\",\"namespace\":\"com.sforce.eventbus\",\"fields\":" +
                "[{\"name\":\"entityName\",\"type\":\"string\"},{\"name\":\"recordIds\",\"type\":{\"type\":\"array" +
                "\",\"items\":\"string\"}},{\"name\":\"changeType\",\"type\":{\"type\":\"enum\",\"name\":\"ChangeTy" +
                "pe\",\"namespace\":\"com.sforce.eventbus\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\",\"UND" +
                "ELETE\",\"GAP_CREATE\",\"GAP_UPDATE\",\"GAP_DELETE\",\"GAP_UNDELETE\",\"GAP_OVERFLOW\"]}},{" +
                "\"name\":\"changeOrigin\",\"type\":\"string\"},{\"name\":\"transactionKey\",\"type\":\"string\"}" +
                ",{\"name\":\"sequenceNumber\",\"type\":\"int\"},{\"name\":\"commitTimestamp\",\"type\":\"long\"}" +
                ",{\"name\":\"commitNumber\",\"type\":\"long\"},{\"name\":\"commitUser\",\"type\":\"string\"},{\"n" +
                "ame\":\"nulledFields\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"diffField" +
                "s\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"changedFields\",\"type\":{\"ty" +
                "pe\":\"array\",\"items\":\"string\"}}]}},{\"name\":\"Name\",\"doc\":\"Data:Switchable_PersonNa" +
                "me\",\"default\":null,\"type\":[\"null\",\"string\",{\"type\":\"record\",\"name\":\"Switchable_P" +
                "ersonName\",\"namespace\":\"com.sforce.eventbus\",\"fields\":[{\"name\":\"Salutation\",\"def" +
                "ault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"FirstName\",\"default\":null,\"type\":[" +
                "\"null\",\"string\"]},{\"name\":\"LastName\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
                "name\":\"MiddleName\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"InformalNam" +
                "e\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Suffix\",\"default\":null,\"typ" +
                "e\":[\"null\",\"string\"]}]}]},{\"name\":\"Type\",\"doc\":\"Data:DynamicEnum\",\"default\":null" +
                ",\"type\":[\"null\",\"string\"]},{\"name\":\"RecordTypeId\",\"doc\":\"ForeignKey:EntityId\",\"d" +
                "efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"ParentId\",\"doc\":\"ForeignKey:Enti" +
                "tyId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"BillingAddress\",\"doc\":\"D" +
                "ata:Address\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Address\",\"na" +
                "mespace\":\"com.sforce.eventbus\",\"fields\":[{\"name\":\"Street\",\"default\":null,\"type\":" +
                "[\"null\",\"string\"]},{\"name\":\"City\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
                "e\":\"State\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PostalCode\",\"defaul" +
                "t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Country\",\"default\":null,\"type\":[\"null" +
                "\",\"string\"]},{\"name\":\"StateCode\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
                "\":\"CountryCode\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Latitude\",\"def" +
                "ault\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Longitude\",\"default\":null,\"type\":[" +
                "\"null\",\"double\"]},{\"name\":\"Xyz\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
                ":\"GeocodeAccuracy\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"Shippin" +
                "gAddress\",\"doc\":\"Data:Address\",\"default\":null,\"type\":[\"null\",\"Address\"]},{\"name\"" +
                ":\"Phone\",\"doc\":\"Data:Phone\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Fa" +
                "x\",\"doc\":\"Data:Fax\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"AccountNum" +
                "ber\",\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Website" +
                "\",\"doc\":\"Data:Url\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Sic\",\"doc\":" +
                "\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Industry\",\"doc\":\"D" +
                "ata:DynamicEnum\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"AnnualRevenue" +
                "\",\"doc\":\"Data:Currency\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Number" +
                "OfEmployees\",\"doc\":\"Data:Integer\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":" +
                "\"Ownership\",\"doc\":\"Data:DynamicEnum\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
                "name\":\"TickerSymbol\",\"doc\":\"Data:Content\",\"default\":null,\"type\":[\"null\",\"string\"" +
                "]},{\"name\":\"Description\",\"doc\":\"Data:StringPlusClob\",\"default\":null,\"type\":[\"nul" +
                "l\",\"string\"]},{\"name\":\"Rating\",\"doc\":\"Data:DynamicEnum\",\"default\":null,\"type\":[\"" +
                "null\",\"string\"]},{\"name\":\"Site\",\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\"," +
                "\"string\"]},{\"name\":\"OwnerId\",\"doc\":\"ForeignKey:EntityId\",\"default\":null,\"type\":[" +
                "\"null\",\"string\"]},{\"name\":\"CreatedDate\",\"doc\":\"CreatedDate:DateTime\",\"default\":n" +
                "ull,\"type\":[\"null\",\"long\"]},{\"name\":\"CreatedById\",\"doc\":\"ForeignKey:EntityId\",\"d" +
                "efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"LastModifiedDate\",\"doc\":\"Data:Da" +
                "teTime\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"LastModifiedById\",\"doc\":" +
                "\"ForeignKey:EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonCo" +
                "ntactId\",\"doc\":\"ForeignKey:EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
                "name\":\"PersonMailingAddress\",\"doc\":\"Data:Address\",\"default\":null,\"type\":[\"null\"," +
                "\"Address\"]},{\"name\":\"PersonOtherAddress\",\"doc\":\"Data:Address\",\"default\":null,\"ty" +
                "pe\":[\"null\",\"Address\"]},{\"name\":\"PersonMobilePhone\",\"doc\":\"Data:Phone\",\"default\"" +
                ":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonHomePhone\",\"doc\":\"Data:Phone\",\"de" +
                "fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonOtherPhone\",\"doc\":\"Data:Pho" +
                "ne\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonAssistantPhone\",\"doc" +
                "\":\"Data:Phone\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonEmail\",\"d" +
                "oc\":\"Data:Email\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonTitle\"," +
                "\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonDepart" +
                "ment\",\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Person" +
                "AssistantName\",\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
                "\":\"PersonLeadSource\",\"doc\":\"Data:DynamicEnum\",\"default\":null,\"type\":[\"null\",\"str" +
                "ing\"]},{\"name\":\"PersonBirthdate\",\"doc\":\"Data:Birthday\",\"default\":null,\"type\":[\"n" +
                "ull\",\"long\"]},{\"name\":\"PersonHasOptedOutOfEmail\",\"doc\":\"Data:Boolean\",\"default\":" +
                "null,\"type\":[\"null\",\"boolean\"]},{\"name\":\"PersonHasOptedOutOfFax\",\"doc\":\"Data:Boo" +
                "lean\",\"default\":null,\"type\":[\"null\",\"boolean\"]},{\"name\":\"PersonDoNotCall\",\"doc\":" +
                "\"Data:Boolean\",\"default\":null,\"type\":[\"null\",\"boolean\"]},{\"name\":\"PersonLastCURe" +
                "questDate\",\"doc\":\"Data:DateTime\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":" +
                "\"PersonLastCUUpdateDate\",\"doc\":\"Data:DateTime\",\"default\":null,\"type\":[\"null\",\"lo" +
                "ng\"]},{\"name\":\"PersonEmailBouncedReason\",\"doc\":\"Data:Text\",\"default\":null,\"type\"" +
                ":[\"null\",\"string\"]},{\"name\":\"PersonEmailBouncedDate\",\"doc\":\"Data:DateTime\",\"defa" +
                "ult\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"PersonIndividualId\",\"doc\":\"ForeignKey" +
                ":EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonPronouns\",\"do" +
                "c\":\"Data:DynamicEnum\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PersonGe" +
                "nderIdentity\",\"doc\":\"Data:DynamicEnum\",\"default\":null,\"type\":[\"null\",\"string\"]}," +
                "{\"name\":\"Jigsaw\",\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
                "me\":\"JigsawCompanyId\",\"doc\":\"ExternalForeignKey:ExternalId\",\"default\":null,\"type" +
                "\":[\"null\",\"string\"]},{\"name\":\"CleanStatus\",\"doc\":\"Data:StaticEnum\",\"default\":nul" +
                "l,\"type\":[\"null\",\"string\"]},{\"name\":\"AccountSource\",\"doc\":\"Data:DynamicEnum\",\"de" +
                "fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"DunsNumber\",\"doc\":\"Data:Text\",\"de" +
                "fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Tradestyle\",\"doc\":\"Data:Text\",\"de" +
                "fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"NaicsCode\",\"doc\":\"Data:Text\",\"def" +
                "ault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"NaicsDesc\",\"doc\":\"Data:Text\",\"defa" +
                "ult\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"YearStarted\",\"doc\":\"Data:Text\",\"def" +
                "ault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"SicDesc\",\"doc\":\"Data:Text\",\"defaul" +
                "t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"DandbCompanyId\",\"doc\":\"ForeignKey:Ent" +
                "ityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"OperatingHoursId\",\"doc\"" +
                ":\"ForeignKey:EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Custome" +
                "rPriority__c\",\"doc\":\"Data:DynamicEnum:00NDp00000BbvCY\",\"default\":null,\"type\":[\"n" +
                "ull\",\"string\"]},{\"name\":\"SLA__c\",\"doc\":\"Data:DynamicEnum:00NDp00000BbvCa\",\"defau" +
                "lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Active__c\",\"doc\":\"Data:DynamicEnum:0" +
                "0NDp00000BbvCX\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"NumberofLocati" +
                "ons__c\",\"doc\":\"Data:Double:00NDp00000BbvCZ\",\"default\":null,\"type\":[\"null\",\"doubl" +
                "e\"]},{\"name\":\"UpsellOpportunity__c\",\"doc\":\"Data:DynamicEnum:00NDp00000BbvCd\",\"de" +
                "fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"SLASerialNumber__c\",\"doc\":\"Data:T" +
                "ext:00NDp00000BbvCc\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"SLAExpira" +
                "tionDate__c\",\"doc\":\"Data:DateOnly:00NDp00000BbvCb\",\"default\":null,\"type\":[\"null\"" +
                ",\"long\"]},{\"name\":\"Some_phone__c\",\"doc\":\"Data:Phone:00NDp000009Rr9c\",\"default\":n" +
                "ull,\"type\":[\"null\",\"string\"]},{\"name\":\"Amount_Owed__c\",\"doc\":\"Data:Currency:00ND" +
                "p000009Rr98\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Some_Date_Time__c" +
                "\",\"doc\":\"Data:DateTime:00NDp000009Rr9D\",\"default\":null,\"type\":[\"null\",\"long\"]},{" +
                "\"name\":\"Some_Date__c\",\"doc\":\"Data:DateOnly:00NDp000009Rr9I\",\"default\":null,\"type" +
                "\":[\"null\",\"long\"]},{\"name\":\"Some_Email__c\",\"doc\":\"Data:Email:00NDp000009Rr99\",\"d" +
                "efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Some_Geolocation__c\",\"doc\":\"Data" +
                ":Location:00NDp000009Rr9N\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\"" +
                ":\"Location\",\"namespace\":\"com.sforce.eventbus\",\"fields\":[{\"name\":\"Latitude\",\"defa" +
                "ult\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Longitude\",\"default\":null,\"type\":[\"" +
                "null\",\"double\"]},{\"name\":\"XyzEncoded\",\"default\":null,\"type\":[\"null\",\"string\"]}]}" +
                "]},{\"name\":\"Some_Number__c\",\"doc\":\"Data:Double:00NDp000009Rr9S\",\"default\":null,\"" +
                "type\":[\"null\",\"double\"]},{\"name\":\"Some_Percent__c\",\"doc\":\"Data:Percent:00NDp0000" +
                "09Rr9X\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Some_Picklist__c\",\"doc" +
                "\":\"Data:DynamicEnum:00NDp000009Rr9h\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
                "name\":\"Some_Multipicklist__c\",\"doc\":\"Data:MultiEnum:00NDp000009Rr9m\",\"default\":n" +
                "ull,\"type\":[\"null\",\"string\"]},{\"name\":\"Some_Text__c\",\"doc\":\"Data:Text:00NDp00000" +
                "9Rr9r\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Some_Rich_Text_Area__c\"" +
                ",\"doc\":\"Data:HtmlStringPlusClob:00NDp000009Rr9w\",\"default\":null,\"type\":[\"null\",\"" +
                "string\"]},{\"name\":\"Some_Time__c\",\"doc\":\"Data:TimeOnly:00NDp000009RrA1\",\"default\"" +
                ":null,\"type\":[\"null\",\"long\"]},{\"name\":\"Some_URL__c\",\"doc\":\"Data:Url:00NDp000009R" +
                "rA6\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"GUID__c\",\"doc\":\"Data:Text" +
                ":00NDp000009RrFl\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Level__pc\",\"" +
                "doc\":\"Data:DynamicEnum:00NDp00000BbvCj\",\"default\":null,\"type\":[\"null\",\"string\"]}" +
                ",{\"name\":\"Languages__pc\",\"doc\":\"Data:Text:00NDp00000BbvCi\",\"default\":null,\"type\"" +
                ":[\"null\",\"string\"]},{\"name\":\"GUID__pc\",\"doc\":\"Data:Text:00NDp000009RrFq\",\"defaul" +
                "t\":null,\"type\":[\"null\",\"string\"]}]}");
        /// <summary>
        /// Data:ComplexValueType
        /// </summary>
        private com.sforce.eventbus.ChangeEventHeader _ChangeEventHeader;
        /// <summary>
        /// Data:Switchable_PersonName
        /// </summary>
        private object _Name;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _Type;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _RecordTypeId;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _ParentId;
        /// <summary>
        /// Data:Address
        /// </summary>
        private com.sforce.eventbus.Address _BillingAddress;
        /// <summary>
        /// Data:Address
        /// </summary>
        private com.sforce.eventbus.Address _ShippingAddress;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _Phone;
        /// <summary>
        /// Data:Fax
        /// </summary>
        private string _Fax;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _AccountNumber;
        /// <summary>
        /// Data:Url
        /// </summary>
        private string _Website;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _Sic;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _Industry;
        /// <summary>
        /// Data:Currency
        /// </summary>
        private System.Nullable<System.Double> _AnnualRevenue;
        /// <summary>
        /// Data:Integer
        /// </summary>
        private System.Nullable<System.Int32> _NumberOfEmployees;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _Ownership;
        /// <summary>
        /// Data:Content
        /// </summary>
        private string _TickerSymbol;
        /// <summary>
        /// Data:StringPlusClob
        /// </summary>
        private string _Description;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _Rating;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _Site;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _OwnerId;
        /// <summary>
        /// CreatedDate:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _CreatedDate;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _CreatedById;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _LastModifiedDate;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _LastModifiedById;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _PersonContactId;
        /// <summary>
        /// Data:Address
        /// </summary>
        private com.sforce.eventbus.Address _PersonMailingAddress;
        /// <summary>
        /// Data:Address
        /// </summary>
        private com.sforce.eventbus.Address _PersonOtherAddress;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _PersonMobilePhone;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _PersonHomePhone;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _PersonOtherPhone;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _PersonAssistantPhone;
        /// <summary>
        /// Data:Email
        /// </summary>
        private string _PersonEmail;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _PersonTitle;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _PersonDepartment;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _PersonAssistantName;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _PersonLeadSource;
        /// <summary>
        /// Data:Birthday
        /// </summary>
        private System.Nullable<System.Int64> _PersonBirthdate;
        /// <summary>
        /// Data:Boolean
        /// </summary>
        private System.Nullable<System.Boolean> _PersonHasOptedOutOfEmail;
        /// <summary>
        /// Data:Boolean
        /// </summary>
        private System.Nullable<System.Boolean> _PersonHasOptedOutOfFax;
        /// <summary>
        /// Data:Boolean
        /// </summary>
        private System.Nullable<System.Boolean> _PersonDoNotCall;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _PersonLastCURequestDate;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _PersonLastCUUpdateDate;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _PersonEmailBouncedReason;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _PersonEmailBouncedDate;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _PersonIndividualId;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _PersonPronouns;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _PersonGenderIdentity;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _Jigsaw;
        /// <summary>
        /// ExternalForeignKey:ExternalId
        /// </summary>
        private string _JigsawCompanyId;
        /// <summary>
        /// Data:StaticEnum
        /// </summary>
        private string _CleanStatus;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _AccountSource;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _DunsNumber;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _Tradestyle;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _NaicsCode;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _NaicsDesc;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _YearStarted;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _SicDesc;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _DandbCompanyId;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _OperatingHoursId;
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCY
        /// </summary>
        private string _CustomerPriority__c;
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCa
        /// </summary>
        private string _SLA__c;
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCX
        /// </summary>
        private string _Active__c;
        /// <summary>
        /// Data:Double:00NDp00000BbvCZ
        /// </summary>
        private System.Nullable<System.Double> _NumberofLocations__c;
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCd
        /// </summary>
        private string _UpsellOpportunity__c;
        /// <summary>
        /// Data:Text:00NDp00000BbvCc
        /// </summary>
        private string _SLASerialNumber__c;
        /// <summary>
        /// Data:DateOnly:00NDp00000BbvCb
        /// </summary>
        private System.Nullable<System.Int64> _SLAExpirationDate__c;
        /// <summary>
        /// Data:Phone:00NDp000009Rr9c
        /// </summary>
        private string _Some_phone__c;
        /// <summary>
        /// Data:Currency:00NDp000009Rr98
        /// </summary>
        private System.Nullable<System.Double> _Amount_Owed__c;
        /// <summary>
        /// Data:DateTime:00NDp000009Rr9D
        /// </summary>
        private System.Nullable<System.Int64> _Some_Date_Time__c;
        /// <summary>
        /// Data:DateOnly:00NDp000009Rr9I
        /// </summary>
        private System.Nullable<System.Int64> _Some_Date__c;
        /// <summary>
        /// Data:Email:00NDp000009Rr99
        /// </summary>
        private string _Some_Email__c;
        /// <summary>
        /// Data:Location:00NDp000009Rr9N
        /// </summary>
        private com.sforce.eventbus.Location _Some_Geolocation__c;
        /// <summary>
        /// Data:Double:00NDp000009Rr9S
        /// </summary>
        private System.Nullable<System.Double> _Some_Number__c;
        /// <summary>
        /// Data:Percent:00NDp000009Rr9X
        /// </summary>
        private System.Nullable<System.Double> _Some_Percent__c;
        /// <summary>
        /// Data:DynamicEnum:00NDp000009Rr9h
        /// </summary>
        private string _Some_Picklist__c;
        /// <summary>
        /// Data:MultiEnum:00NDp000009Rr9m
        /// </summary>
        private string _Some_Multipicklist__c;
        /// <summary>
        /// Data:Text:00NDp000009Rr9r
        /// </summary>
        private string _Some_Text__c;
        /// <summary>
        /// Data:HtmlStringPlusClob:00NDp000009Rr9w
        /// </summary>
        private string _Some_Rich_Text_Area__c;
        /// <summary>
        /// Data:TimeOnly:00NDp000009RrA1
        /// </summary>
        private System.Nullable<System.Int64> _Some_Time__c;
        /// <summary>
        /// Data:Url:00NDp000009RrA6
        /// </summary>
        private string _Some_URL__c;
        /// <summary>
        /// Data:Text:00NDp000009RrFl
        /// </summary>
        private string _GUID__c;
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCj
        /// </summary>
        private string _Level__pc;
        /// <summary>
        /// Data:Text:00NDp00000BbvCi
        /// </summary>
        private string _Languages__pc;
        /// <summary>
        /// Data:Text:00NDp000009RrFq
        /// </summary>
        private string _GUID__pc;
        public virtual global::Avro.Schema Schema {
            get {
                return AccountChangeEvent._SCHEMA;
            }
        }
        /// <summary>
        /// Data:ComplexValueType
        /// </summary>
        public com.sforce.eventbus.ChangeEventHeader ChangeEventHeader {
            get {
                return this._ChangeEventHeader;
            }
            set {
                this._ChangeEventHeader = value;
            }
        }
        /// <summary>
        /// Data:Switchable_PersonName
        /// </summary>
        public object Name {
            get {
                return this._Name;
            }
            set {
                this._Name = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string Type {
            get {
                return this._Type;
            }
            set {
                this._Type = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string RecordTypeId {
            get {
                return this._RecordTypeId;
            }
            set {
                this._RecordTypeId = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string ParentId {
            get {
                return this._ParentId;
            }
            set {
                this._ParentId = value;
            }
        }
        /// <summary>
        /// Data:Address
        /// </summary>
        public com.sforce.eventbus.Address BillingAddress {
            get {
                return this._BillingAddress;
            }
            set {
                this._BillingAddress = value;
            }
        }
        /// <summary>
        /// Data:Address
        /// </summary>
        public com.sforce.eventbus.Address ShippingAddress {
            get {
                return this._ShippingAddress;
            }
            set {
                this._ShippingAddress = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string Phone {
            get {
                return this._Phone;
            }
            set {
                this._Phone = value;
            }
        }
        /// <summary>
        /// Data:Fax
        /// </summary>
        public string Fax {
            get {
                return this._Fax;
            }
            set {
                this._Fax = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string AccountNumber {
            get {
                return this._AccountNumber;
            }
            set {
                this._AccountNumber = value;
            }
        }
        /// <summary>
        /// Data:Url
        /// </summary>
        public string Website {
            get {
                return this._Website;
            }
            set {
                this._Website = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string Sic {
            get {
                return this._Sic;
            }
            set {
                this._Sic = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string Industry {
            get {
                return this._Industry;
            }
            set {
                this._Industry = value;
            }
        }
        /// <summary>
        /// Data:Currency
        /// </summary>
        public System.Nullable<System.Double> AnnualRevenue {
            get {
                return this._AnnualRevenue;
            }
            set {
                this._AnnualRevenue = value;
            }
        }
        /// <summary>
        /// Data:Integer
        /// </summary>
        public System.Nullable<System.Int32> NumberOfEmployees {
            get {
                return this._NumberOfEmployees;
            }
            set {
                this._NumberOfEmployees = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string Ownership {
            get {
                return this._Ownership;
            }
            set {
                this._Ownership = value;
            }
        }
        /// <summary>
        /// Data:Content
        /// </summary>
        public string TickerSymbol {
            get {
                return this._TickerSymbol;
            }
            set {
                this._TickerSymbol = value;
            }
        }
        /// <summary>
        /// Data:StringPlusClob
        /// </summary>
        public string Description {
            get {
                return this._Description;
            }
            set {
                this._Description = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string Rating {
            get {
                return this._Rating;
            }
            set {
                this._Rating = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string Site {
            get {
                return this._Site;
            }
            set {
                this._Site = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string OwnerId {
            get {
                return this._OwnerId;
            }
            set {
                this._OwnerId = value;
            }
        }
        /// <summary>
        /// CreatedDate:DateTime
        /// </summary>
        public System.Nullable<System.Int64> CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string CreatedById {
            get {
                return this._CreatedById;
            }
            set {
                this._CreatedById = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> LastModifiedDate {
            get {
                return this._LastModifiedDate;
            }
            set {
                this._LastModifiedDate = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string LastModifiedById {
            get {
                return this._LastModifiedById;
            }
            set {
                this._LastModifiedById = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string PersonContactId {
            get {
                return this._PersonContactId;
            }
            set {
                this._PersonContactId = value;
            }
        }
        /// <summary>
        /// Data:Address
        /// </summary>
        public com.sforce.eventbus.Address PersonMailingAddress {
            get {
                return this._PersonMailingAddress;
            }
            set {
                this._PersonMailingAddress = value;
            }
        }
        /// <summary>
        /// Data:Address
        /// </summary>
        public com.sforce.eventbus.Address PersonOtherAddress {
            get {
                return this._PersonOtherAddress;
            }
            set {
                this._PersonOtherAddress = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string PersonMobilePhone {
            get {
                return this._PersonMobilePhone;
            }
            set {
                this._PersonMobilePhone = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string PersonHomePhone {
            get {
                return this._PersonHomePhone;
            }
            set {
                this._PersonHomePhone = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string PersonOtherPhone {
            get {
                return this._PersonOtherPhone;
            }
            set {
                this._PersonOtherPhone = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string PersonAssistantPhone {
            get {
                return this._PersonAssistantPhone;
            }
            set {
                this._PersonAssistantPhone = value;
            }
        }
        /// <summary>
        /// Data:Email
        /// </summary>
        public string PersonEmail {
            get {
                return this._PersonEmail;
            }
            set {
                this._PersonEmail = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string PersonTitle {
            get {
                return this._PersonTitle;
            }
            set {
                this._PersonTitle = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string PersonDepartment {
            get {
                return this._PersonDepartment;
            }
            set {
                this._PersonDepartment = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string PersonAssistantName {
            get {
                return this._PersonAssistantName;
            }
            set {
                this._PersonAssistantName = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string PersonLeadSource {
            get {
                return this._PersonLeadSource;
            }
            set {
                this._PersonLeadSource = value;
            }
        }
        /// <summary>
        /// Data:Birthday
        /// </summary>
        public System.Nullable<System.Int64> PersonBirthdate {
            get {
                return this._PersonBirthdate;
            }
            set {
                this._PersonBirthdate = value;
            }
        }
        /// <summary>
        /// Data:Boolean
        /// </summary>
        public System.Nullable<System.Boolean> PersonHasOptedOutOfEmail {
            get {
                return this._PersonHasOptedOutOfEmail;
            }
            set {
                this._PersonHasOptedOutOfEmail = value;
            }
        }
        /// <summary>
        /// Data:Boolean
        /// </summary>
        public System.Nullable<System.Boolean> PersonHasOptedOutOfFax {
            get {
                return this._PersonHasOptedOutOfFax;
            }
            set {
                this._PersonHasOptedOutOfFax = value;
            }
        }
        /// <summary>
        /// Data:Boolean
        /// </summary>
        public System.Nullable<System.Boolean> PersonDoNotCall {
            get {
                return this._PersonDoNotCall;
            }
            set {
                this._PersonDoNotCall = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> PersonLastCURequestDate {
            get {
                return this._PersonLastCURequestDate;
            }
            set {
                this._PersonLastCURequestDate = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> PersonLastCUUpdateDate {
            get {
                return this._PersonLastCUUpdateDate;
            }
            set {
                this._PersonLastCUUpdateDate = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string PersonEmailBouncedReason {
            get {
                return this._PersonEmailBouncedReason;
            }
            set {
                this._PersonEmailBouncedReason = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> PersonEmailBouncedDate {
            get {
                return this._PersonEmailBouncedDate;
            }
            set {
                this._PersonEmailBouncedDate = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string PersonIndividualId {
            get {
                return this._PersonIndividualId;
            }
            set {
                this._PersonIndividualId = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string PersonPronouns {
            get {
                return this._PersonPronouns;
            }
            set {
                this._PersonPronouns = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string PersonGenderIdentity {
            get {
                return this._PersonGenderIdentity;
            }
            set {
                this._PersonGenderIdentity = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string Jigsaw {
            get {
                return this._Jigsaw;
            }
            set {
                this._Jigsaw = value;
            }
        }
        /// <summary>
        /// ExternalForeignKey:ExternalId
        /// </summary>
        public string JigsawCompanyId {
            get {
                return this._JigsawCompanyId;
            }
            set {
                this._JigsawCompanyId = value;
            }
        }
        /// <summary>
        /// Data:StaticEnum
        /// </summary>
        public string CleanStatus {
            get {
                return this._CleanStatus;
            }
            set {
                this._CleanStatus = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string AccountSource {
            get {
                return this._AccountSource;
            }
            set {
                this._AccountSource = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string DunsNumber {
            get {
                return this._DunsNumber;
            }
            set {
                this._DunsNumber = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string Tradestyle {
            get {
                return this._Tradestyle;
            }
            set {
                this._Tradestyle = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string NaicsCode {
            get {
                return this._NaicsCode;
            }
            set {
                this._NaicsCode = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string NaicsDesc {
            get {
                return this._NaicsDesc;
            }
            set {
                this._NaicsDesc = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string YearStarted {
            get {
                return this._YearStarted;
            }
            set {
                this._YearStarted = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string SicDesc {
            get {
                return this._SicDesc;
            }
            set {
                this._SicDesc = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string DandbCompanyId {
            get {
                return this._DandbCompanyId;
            }
            set {
                this._DandbCompanyId = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string OperatingHoursId {
            get {
                return this._OperatingHoursId;
            }
            set {
                this._OperatingHoursId = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCY
        /// </summary>
        public string CustomerPriority__c {
            get {
                return this._CustomerPriority__c;
            }
            set {
                this._CustomerPriority__c = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCa
        /// </summary>
        public string SLA__c {
            get {
                return this._SLA__c;
            }
            set {
                this._SLA__c = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCX
        /// </summary>
        public string Active__c {
            get {
                return this._Active__c;
            }
            set {
                this._Active__c = value;
            }
        }
        /// <summary>
        /// Data:Double:00NDp00000BbvCZ
        /// </summary>
        public System.Nullable<System.Double> NumberofLocations__c {
            get {
                return this._NumberofLocations__c;
            }
            set {
                this._NumberofLocations__c = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCd
        /// </summary>
        public string UpsellOpportunity__c {
            get {
                return this._UpsellOpportunity__c;
            }
            set {
                this._UpsellOpportunity__c = value;
            }
        }
        /// <summary>
        /// Data:Text:00NDp00000BbvCc
        /// </summary>
        public string SLASerialNumber__c {
            get {
                return this._SLASerialNumber__c;
            }
            set {
                this._SLASerialNumber__c = value;
            }
        }
        /// <summary>
        /// Data:DateOnly:00NDp00000BbvCb
        /// </summary>
        public System.Nullable<System.Int64> SLAExpirationDate__c {
            get {
                return this._SLAExpirationDate__c;
            }
            set {
                this._SLAExpirationDate__c = value;
            }
        }
        /// <summary>
        /// Data:Phone:00NDp000009Rr9c
        /// </summary>
        public string Some_phone__c {
            get {
                return this._Some_phone__c;
            }
            set {
                this._Some_phone__c = value;
            }
        }
        /// <summary>
        /// Data:Currency:00NDp000009Rr98
        /// </summary>
        public System.Nullable<System.Double> Amount_Owed__c {
            get {
                return this._Amount_Owed__c;
            }
            set {
                this._Amount_Owed__c = value;
            }
        }
        /// <summary>
        /// Data:DateTime:00NDp000009Rr9D
        /// </summary>
        public System.Nullable<System.Int64> Some_Date_Time__c {
            get {
                return this._Some_Date_Time__c;
            }
            set {
                this._Some_Date_Time__c = value;
            }
        }
        /// <summary>
        /// Data:DateOnly:00NDp000009Rr9I
        /// </summary>
        public System.Nullable<System.Int64> Some_Date__c {
            get {
                return this._Some_Date__c;
            }
            set {
                this._Some_Date__c = value;
            }
        }
        /// <summary>
        /// Data:Email:00NDp000009Rr99
        /// </summary>
        public string Some_Email__c {
            get {
                return this._Some_Email__c;
            }
            set {
                this._Some_Email__c = value;
            }
        }
        /// <summary>
        /// Data:Location:00NDp000009Rr9N
        /// </summary>
        public com.sforce.eventbus.Location Some_Geolocation__c {
            get {
                return this._Some_Geolocation__c;
            }
            set {
                this._Some_Geolocation__c = value;
            }
        }
        /// <summary>
        /// Data:Double:00NDp000009Rr9S
        /// </summary>
        public System.Nullable<System.Double> Some_Number__c {
            get {
                return this._Some_Number__c;
            }
            set {
                this._Some_Number__c = value;
            }
        }
        /// <summary>
        /// Data:Percent:00NDp000009Rr9X
        /// </summary>
        public System.Nullable<System.Double> Some_Percent__c {
            get {
                return this._Some_Percent__c;
            }
            set {
                this._Some_Percent__c = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum:00NDp000009Rr9h
        /// </summary>
        public string Some_Picklist__c {
            get {
                return this._Some_Picklist__c;
            }
            set {
                this._Some_Picklist__c = value;
            }
        }
        /// <summary>
        /// Data:MultiEnum:00NDp000009Rr9m
        /// </summary>
        public string Some_Multipicklist__c {
            get {
                return this._Some_Multipicklist__c;
            }
            set {
                this._Some_Multipicklist__c = value;
            }
        }
        /// <summary>
        /// Data:Text:00NDp000009Rr9r
        /// </summary>
        public string Some_Text__c {
            get {
                return this._Some_Text__c;
            }
            set {
                this._Some_Text__c = value;
            }
        }
        /// <summary>
        /// Data:HtmlStringPlusClob:00NDp000009Rr9w
        /// </summary>
        public string Some_Rich_Text_Area__c {
            get {
                return this._Some_Rich_Text_Area__c;
            }
            set {
                this._Some_Rich_Text_Area__c = value;
            }
        }
        /// <summary>
        /// Data:TimeOnly:00NDp000009RrA1
        /// </summary>
        public System.Nullable<System.Int64> Some_Time__c {
            get {
                return this._Some_Time__c;
            }
            set {
                this._Some_Time__c = value;
            }
        }
        /// <summary>
        /// Data:Url:00NDp000009RrA6
        /// </summary>
        public string Some_URL__c {
            get {
                return this._Some_URL__c;
            }
            set {
                this._Some_URL__c = value;
            }
        }
        /// <summary>
        /// Data:Text:00NDp000009RrFl
        /// </summary>
        public string GUID__c {
            get {
                return this._GUID__c;
            }
            set {
                this._GUID__c = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCj
        /// </summary>
        public string Level__pc {
            get {
                return this._Level__pc;
            }
            set {
                this._Level__pc = value;
            }
        }
        /// <summary>
        /// Data:Text:00NDp00000BbvCi
        /// </summary>
        public string Languages__pc {
            get {
                return this._Languages__pc;
            }
            set {
                this._Languages__pc = value;
            }
        }
        /// <summary>
        /// Data:Text:00NDp000009RrFq
        /// </summary>
        public string GUID__pc {
            get {
                return this._GUID__pc;
            }
            set {
                this._GUID__pc = value;
            }
        }
        public virtual object Get(int fieldPos) {
            switch (fieldPos) {
                case 0: return this.ChangeEventHeader;
                case 1: return this.Name;
                case 2: return this.Type;
                case 3: return this.RecordTypeId;
                case 4: return this.ParentId;
                case 5: return this.BillingAddress;
                case 6: return this.ShippingAddress;
                case 7: return this.Phone;
                case 8: return this.Fax;
                case 9: return this.AccountNumber;
                case 10: return this.Website;
                case 11: return this.Sic;
                case 12: return this.Industry;
                case 13: return this.AnnualRevenue;
                case 14: return this.NumberOfEmployees;
                case 15: return this.Ownership;
                case 16: return this.TickerSymbol;
                case 17: return this.Description;
                case 18: return this.Rating;
                case 19: return this.Site;
                case 20: return this.OwnerId;
                case 21: return this.CreatedDate;
                case 22: return this.CreatedById;
                case 23: return this.LastModifiedDate;
                case 24: return this.LastModifiedById;
                case 25: return this.PersonContactId;
                case 26: return this.PersonMailingAddress;
                case 27: return this.PersonOtherAddress;
                case 28: return this.PersonMobilePhone;
                case 29: return this.PersonHomePhone;
                case 30: return this.PersonOtherPhone;
                case 31: return this.PersonAssistantPhone;
                case 32: return this.PersonEmail;
                case 33: return this.PersonTitle;
                case 34: return this.PersonDepartment;
                case 35: return this.PersonAssistantName;
                case 36: return this.PersonLeadSource;
                case 37: return this.PersonBirthdate;
                case 38: return this.PersonHasOptedOutOfEmail;
                case 39: return this.PersonHasOptedOutOfFax;
                case 40: return this.PersonDoNotCall;
                case 41: return this.PersonLastCURequestDate;
                case 42: return this.PersonLastCUUpdateDate;
                case 43: return this.PersonEmailBouncedReason;
                case 44: return this.PersonEmailBouncedDate;
                case 45: return this.PersonIndividualId;
                case 46: return this.PersonPronouns;
                case 47: return this.PersonGenderIdentity;
                case 48: return this.Jigsaw;
                case 49: return this.JigsawCompanyId;
                case 50: return this.CleanStatus;
                case 51: return this.AccountSource;
                case 52: return this.DunsNumber;
                case 53: return this.Tradestyle;
                case 54: return this.NaicsCode;
                case 55: return this.NaicsDesc;
                case 56: return this.YearStarted;
                case 57: return this.SicDesc;
                case 58: return this.DandbCompanyId;
                case 59: return this.OperatingHoursId;
                case 60: return this.CustomerPriority__c;
                case 61: return this.SLA__c;
                case 62: return this.Active__c;
                case 63: return this.NumberofLocations__c;
                case 64: return this.UpsellOpportunity__c;
                case 65: return this.SLASerialNumber__c;
                case 66: return this.SLAExpirationDate__c;
                case 67: return this.Some_phone__c;
                case 68: return this.Amount_Owed__c;
                case 69: return this.Some_Date_Time__c;
                case 70: return this.Some_Date__c;
                case 71: return this.Some_Email__c;
                case 72: return this.Some_Geolocation__c;
                case 73: return this.Some_Number__c;
                case 74: return this.Some_Percent__c;
                case 75: return this.Some_Picklist__c;
                case 76: return this.Some_Multipicklist__c;
                case 77: return this.Some_Text__c;
                case 78: return this.Some_Rich_Text_Area__c;
                case 79: return this.Some_Time__c;
                case 80: return this.Some_URL__c;
                case 81: return this.GUID__c;
                case 82: return this.Level__pc;
                case 83: return this.Languages__pc;
                case 84: return this.GUID__pc;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue) {
            switch (fieldPos) {
                case 0: this.ChangeEventHeader = (com.sforce.eventbus.ChangeEventHeader)fieldValue; break;
                case 1: this.Name = (System.Object)fieldValue; break;
                case 2: this.Type = (System.String)fieldValue; break;
                case 3: this.RecordTypeId = (System.String)fieldValue; break;
                case 4: this.ParentId = (System.String)fieldValue; break;
                case 5: this.BillingAddress = (com.sforce.eventbus.Address)fieldValue; break;
                case 6: this.ShippingAddress = (com.sforce.eventbus.Address)fieldValue; break;
                case 7: this.Phone = (System.String)fieldValue; break;
                case 8: this.Fax = (System.String)fieldValue; break;
                case 9: this.AccountNumber = (System.String)fieldValue; break;
                case 10: this.Website = (System.String)fieldValue; break;
                case 11: this.Sic = (System.String)fieldValue; break;
                case 12: this.Industry = (System.String)fieldValue; break;
                case 13: this.AnnualRevenue = (System.Nullable<System.Double>)fieldValue; break;
                case 14: this.NumberOfEmployees = (System.Nullable<System.Int32>)fieldValue; break;
                case 15: this.Ownership = (System.String)fieldValue; break;
                case 16: this.TickerSymbol = (System.String)fieldValue; break;
                case 17: this.Description = (System.String)fieldValue; break;
                case 18: this.Rating = (System.String)fieldValue; break;
                case 19: this.Site = (System.String)fieldValue; break;
                case 20: this.OwnerId = (System.String)fieldValue; break;
                case 21: this.CreatedDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 22: this.CreatedById = (System.String)fieldValue; break;
                case 23: this.LastModifiedDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 24: this.LastModifiedById = (System.String)fieldValue; break;
                case 25: this.PersonContactId = (System.String)fieldValue; break;
                case 26: this.PersonMailingAddress = (com.sforce.eventbus.Address)fieldValue; break;
                case 27: this.PersonOtherAddress = (com.sforce.eventbus.Address)fieldValue; break;
                case 28: this.PersonMobilePhone = (System.String)fieldValue; break;
                case 29: this.PersonHomePhone = (System.String)fieldValue; break;
                case 30: this.PersonOtherPhone = (System.String)fieldValue; break;
                case 31: this.PersonAssistantPhone = (System.String)fieldValue; break;
                case 32: this.PersonEmail = (System.String)fieldValue; break;
                case 33: this.PersonTitle = (System.String)fieldValue; break;
                case 34: this.PersonDepartment = (System.String)fieldValue; break;
                case 35: this.PersonAssistantName = (System.String)fieldValue; break;
                case 36: this.PersonLeadSource = (System.String)fieldValue; break;
                case 37: this.PersonBirthdate = (System.Nullable<System.Int64>)fieldValue; break;
                case 38: this.PersonHasOptedOutOfEmail = (System.Nullable<System.Boolean>)fieldValue; break;
                case 39: this.PersonHasOptedOutOfFax = (System.Nullable<System.Boolean>)fieldValue; break;
                case 40: this.PersonDoNotCall = (System.Nullable<System.Boolean>)fieldValue; break;
                case 41: this.PersonLastCURequestDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 42: this.PersonLastCUUpdateDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 43: this.PersonEmailBouncedReason = (System.String)fieldValue; break;
                case 44: this.PersonEmailBouncedDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 45: this.PersonIndividualId = (System.String)fieldValue; break;
                case 46: this.PersonPronouns = (System.String)fieldValue; break;
                case 47: this.PersonGenderIdentity = (System.String)fieldValue; break;
                case 48: this.Jigsaw = (System.String)fieldValue; break;
                case 49: this.JigsawCompanyId = (System.String)fieldValue; break;
                case 50: this.CleanStatus = (System.String)fieldValue; break;
                case 51: this.AccountSource = (System.String)fieldValue; break;
                case 52: this.DunsNumber = (System.String)fieldValue; break;
                case 53: this.Tradestyle = (System.String)fieldValue; break;
                case 54: this.NaicsCode = (System.String)fieldValue; break;
                case 55: this.NaicsDesc = (System.String)fieldValue; break;
                case 56: this.YearStarted = (System.String)fieldValue; break;
                case 57: this.SicDesc = (System.String)fieldValue; break;
                case 58: this.DandbCompanyId = (System.String)fieldValue; break;
                case 59: this.OperatingHoursId = (System.String)fieldValue; break;
                case 60: this.CustomerPriority__c = (System.String)fieldValue; break;
                case 61: this.SLA__c = (System.String)fieldValue; break;
                case 62: this.Active__c = (System.String)fieldValue; break;
                case 63: this.NumberofLocations__c = (System.Nullable<System.Double>)fieldValue; break;
                case 64: this.UpsellOpportunity__c = (System.String)fieldValue; break;
                case 65: this.SLASerialNumber__c = (System.String)fieldValue; break;
                case 66: this.SLAExpirationDate__c = (System.Nullable<System.Int64>)fieldValue; break;
                case 67: this.Some_phone__c = (System.String)fieldValue; break;
                case 68: this.Amount_Owed__c = (System.Nullable<System.Double>)fieldValue; break;
                case 69: this.Some_Date_Time__c = (System.Nullable<System.Int64>)fieldValue; break;
                case 70: this.Some_Date__c = (System.Nullable<System.Int64>)fieldValue; break;
                case 71: this.Some_Email__c = (System.String)fieldValue; break;
                case 72: this.Some_Geolocation__c = (com.sforce.eventbus.Location)fieldValue; break;
                case 73: this.Some_Number__c = (System.Nullable<System.Double>)fieldValue; break;
                case 74: this.Some_Percent__c = (System.Nullable<System.Double>)fieldValue; break;
                case 75: this.Some_Picklist__c = (System.String)fieldValue; break;
                case 76: this.Some_Multipicklist__c = (System.String)fieldValue; break;
                case 77: this.Some_Text__c = (System.String)fieldValue; break;
                case 78: this.Some_Rich_Text_Area__c = (System.String)fieldValue; break;
                case 79: this.Some_Time__c = (System.Nullable<System.Int64>)fieldValue; break;
                case 80: this.Some_URL__c = (System.String)fieldValue; break;
                case 81: this.GUID__c = (System.String)fieldValue; break;
                case 82: this.Level__pc = (System.String)fieldValue; break;
                case 83: this.Languages__pc = (System.String)fieldValue; break;
                case 84: this.GUID__pc = (System.String)fieldValue; break;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
