// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.sforce.eventbus {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
    public partial class Address : global::Avro.Specific.ISpecificRecord {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Address"",""namespace"":""com.sforce.eventbus"",""fields"":[{""name"":""Street"",""default"":null,""type"":[""null"",""string""]},{""name"":""City"",""default"":null,""type"":[""null"",""string""]},{""name"":""State"",""default"":null,""type"":[""null"",""string""]},{""name"":""PostalCode"",""default"":null,""type"":[""null"",""string""]},{""name"":""Country"",""default"":null,""type"":[""null"",""string""]},{""name"":""StateCode"",""default"":null,""type"":[""null"",""string""]},{""name"":""CountryCode"",""default"":null,""type"":[""null"",""string""]},{""name"":""Latitude"",""default"":null,""type"":[""null"",""double""]},{""name"":""Longitude"",""default"":null,""type"":[""null"",""double""]},{""name"":""Xyz"",""default"":null,""type"":[""null"",""string""]},{""name"":""GeocodeAccuracy"",""default"":null,""type"":[""null"",""string""]}]}");
        private string _Street;
        private string _City;
        private string _State;
        private string _PostalCode;
        private string _Country;
        private string _StateCode;
        private string _CountryCode;
        private System.Nullable<System.Double> _Latitude;
        private System.Nullable<System.Double> _Longitude;
        private string _Xyz;
        private string _GeocodeAccuracy;
        public virtual global::Avro.Schema Schema {
            get {
                return Address._SCHEMA;
            }
        }
        public string Street {
            get {
                return this._Street;
            }
            set {
                this._Street = value;
            }
        }
        public string City {
            get {
                return this._City;
            }
            set {
                this._City = value;
            }
        }
        public string State {
            get {
                return this._State;
            }
            set {
                this._State = value;
            }
        }
        public string PostalCode {
            get {
                return this._PostalCode;
            }
            set {
                this._PostalCode = value;
            }
        }
        public string Country {
            get {
                return this._Country;
            }
            set {
                this._Country = value;
            }
        }
        public string StateCode {
            get {
                return this._StateCode;
            }
            set {
                this._StateCode = value;
            }
        }
        public string CountryCode {
            get {
                return this._CountryCode;
            }
            set {
                this._CountryCode = value;
            }
        }
        public System.Nullable<System.Double> Latitude {
            get {
                return this._Latitude;
            }
            set {
                this._Latitude = value;
            }
        }
        public System.Nullable<System.Double> Longitude {
            get {
                return this._Longitude;
            }
            set {
                this._Longitude = value;
            }
        }
        public string Xyz {
            get {
                return this._Xyz;
            }
            set {
                this._Xyz = value;
            }
        }
        public string GeocodeAccuracy {
            get {
                return this._GeocodeAccuracy;
            }
            set {
                this._GeocodeAccuracy = value;
            }
        }
        public virtual object Get(int fieldPos) {
            switch (fieldPos) {
                case 0: return this.Street;
                case 1: return this.City;
                case 2: return this.State;
                case 3: return this.PostalCode;
                case 4: return this.Country;
                case 5: return this.StateCode;
                case 6: return this.CountryCode;
                case 7: return this.Latitude;
                case 8: return this.Longitude;
                case 9: return this.Xyz;
                case 10: return this.GeocodeAccuracy;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue) {
            switch (fieldPos) {
                case 0: this.Street = (System.String)fieldValue; break;
                case 1: this.City = (System.String)fieldValue; break;
                case 2: this.State = (System.String)fieldValue; break;
                case 3: this.PostalCode = (System.String)fieldValue; break;
                case 4: this.Country = (System.String)fieldValue; break;
                case 5: this.StateCode = (System.String)fieldValue; break;
                case 6: this.CountryCode = (System.String)fieldValue; break;
                case 7: this.Latitude = (System.Nullable<System.Double>)fieldValue; break;
                case 8: this.Longitude = (System.Nullable<System.Double>)fieldValue; break;
                case 9: this.Xyz = (System.String)fieldValue; break;
                case 10: this.GeocodeAccuracy = (System.String)fieldValue; break;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
