// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.sforce.eventbus {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
    public enum ChangeType {
        CREATE,
        UPDATE,
        DELETE,
        UNDELETE,
        GAP_CREATE,
        GAP_UPDATE,
        GAP_DELETE,
        GAP_UNDELETE,
        GAP_OVERFLOW,
    }
}
