// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.sforce.eventbus {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
    public partial class ContactChangeEvent : global::Avro.Specific.ISpecificRecord {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ContactChangeEvent\",\"namespace\":\"com.sforce.eventbus\",\"f" +
                "ields\":[{\"name\":\"ChangeEventHeader\",\"doc\":\"Data:ComplexValueType\",\"type\":{\"type\"" +
                ":\"record\",\"name\":\"ChangeEventHeader\",\"namespace\":\"com.sforce.eventbus\",\"fields\":" +
                "[{\"name\":\"entityName\",\"type\":\"string\"},{\"name\":\"recordIds\",\"type\":{\"type\":\"array" +
                "\",\"items\":\"string\"}},{\"name\":\"changeType\",\"type\":{\"type\":\"enum\",\"name\":\"ChangeTy" +
                "pe\",\"namespace\":\"com.sforce.eventbus\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\",\"UND" +
                "ELETE\",\"GAP_CREATE\",\"GAP_UPDATE\",\"GAP_DELETE\",\"GAP_UNDELETE\",\"GAP_OVERFLOW\"]}},{" +
                "\"name\":\"changeOrigin\",\"type\":\"string\"},{\"name\":\"transactionKey\",\"type\":\"string\"}" +
                ",{\"name\":\"sequenceNumber\",\"type\":\"int\"},{\"name\":\"commitTimestamp\",\"type\":\"long\"}" +
                ",{\"name\":\"commitNumber\",\"type\":\"long\"},{\"name\":\"commitUser\",\"type\":\"string\"},{\"n" +
                "ame\":\"nulledFields\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"diffField" +
                "s\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"changedFields\",\"type\":{\"ty" +
                "pe\":\"array\",\"items\":\"string\"}}]}},{\"name\":\"AccountId\",\"doc\":\"ForeignKey:EntityId" +
                "\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"IsPersonAccount\",\"doc\":\"Data" +
                ":Boolean\",\"default\":null,\"type\":[\"null\",\"boolean\"]},{\"name\":\"Name\",\"doc\":\"Data:P" +
                "ersonName\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"PersonName\",\"n" +
                "amespace\":\"com.sforce.eventbus\",\"fields\":[{\"name\":\"Salutation\",\"default\":null,\"t" +
                "ype\":[\"null\",\"string\"]},{\"name\":\"FirstName\",\"default\":null,\"type\":[\"null\",\"strin" +
                "g\"]},{\"name\":\"LastName\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Middle" +
                "Name\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"InformalName\",\"default\":" +
                "null,\"type\":[\"null\",\"string\"]},{\"name\":\"Suffix\",\"default\":null,\"type\":[\"null\",\"s" +
                "tring\"]}]}]},{\"name\":\"OtherAddress\",\"doc\":\"Data:Address\",\"default\":null,\"type\":[" +
                "\"null\",{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.sforce.eventbus\",\"fiel" +
                "ds\":[{\"name\":\"Street\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"City\",\"d" +
                "efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"State\",\"default\":null,\"type\":[\"n" +
                "ull\",\"string\"]},{\"name\":\"PostalCode\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
                "name\":\"Country\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"StateCode\",\"de" +
                "fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"CountryCode\",\"default\":null,\"type" +
                "\":[\"null\",\"string\"]},{\"name\":\"Latitude\",\"default\":null,\"type\":[\"null\",\"double\"]}" +
                ",{\"name\":\"Longitude\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Xyz\",\"def" +
                "ault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"GeocodeAccuracy\",\"default\":null,\"t" +
                "ype\":[\"null\",\"string\"]}]}]},{\"name\":\"MailingAddress\",\"doc\":\"Data:Address\",\"defau" +
                "lt\":null,\"type\":[\"null\",\"Address\"]},{\"name\":\"Phone\",\"doc\":\"Data:Phone\",\"default\"" +
                ":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Fax\",\"doc\":\"Data:Fax\",\"default\":null,\"t" +
                "ype\":[\"null\",\"string\"]},{\"name\":\"MobilePhone\",\"doc\":\"Data:Phone\",\"default\":null," +
                "\"type\":[\"null\",\"string\"]},{\"name\":\"HomePhone\",\"doc\":\"Data:Phone\",\"default\":null," +
                "\"type\":[\"null\",\"string\"]},{\"name\":\"OtherPhone\",\"doc\":\"Data:Phone\",\"default\":null" +
                ",\"type\":[\"null\",\"string\"]},{\"name\":\"AssistantPhone\",\"doc\":\"Data:Phone\",\"default\"" +
                ":null,\"type\":[\"null\",\"string\"]},{\"name\":\"ReportsToId\",\"doc\":\"ForeignKey:EntityId" +
                "\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Email\",\"doc\":\"Data:Email\",\"d" +
                "efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Title\",\"doc\":\"Data:Text\",\"defaul" +
                "t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Department\",\"doc\":\"Data:Text\",\"defaul" +
                "t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"AssistantName\",\"doc\":\"Data:Text\",\"def" +
                "ault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"LeadSource\",\"doc\":\"Data:DynamicEnu" +
                "m\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Birthdate\",\"doc\":\"Data:Birt" +
                "hday\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"Description\",\"doc\":\"Data:S" +
                "tringPlusClob\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"OwnerId\",\"doc\":" +
                "\"ForeignKey:EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"HasOpted" +
                "OutOfEmail\",\"doc\":\"Data:Boolean\",\"default\":null,\"type\":[\"null\",\"boolean\"]},{\"nam" +
                "e\":\"HasOptedOutOfFax\",\"doc\":\"Data:Boolean\",\"default\":null,\"type\":[\"null\",\"boolea" +
                "n\"]},{\"name\":\"DoNotCall\",\"doc\":\"Data:Boolean\",\"default\":null,\"type\":[\"null\",\"boo" +
                "lean\"]},{\"name\":\"CreatedDate\",\"doc\":\"CreatedDate:DateTime\",\"default\":null,\"type\"" +
                ":[\"null\",\"long\"]},{\"name\":\"CreatedById\",\"doc\":\"ForeignKey:EntityId\",\"default\":nu" +
                "ll,\"type\":[\"null\",\"string\"]},{\"name\":\"LastModifiedDate\",\"doc\":\"Data:DateTime\",\"d" +
                "efault\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"LastModifiedById\",\"doc\":\"ForeignKe" +
                "y:EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"LastCURequestDate\"" +
                ",\"doc\":\"Data:DateTime\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"LastCUUpd" +
                "ateDate\",\"doc\":\"Data:DateTime\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"E" +
                "mailBouncedReason\",\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
                "name\":\"EmailBouncedDate\",\"doc\":\"Data:DateTime\",\"default\":null,\"type\":[\"null\",\"lo" +
                "ng\"]},{\"name\":\"Jigsaw\",\"doc\":\"Data:Text\",\"default\":null,\"type\":[\"null\",\"string\"]" +
                "},{\"name\":\"JigsawContactId\",\"doc\":\"ExternalForeignKey:ExternalId\",\"default\":null" +
                ",\"type\":[\"null\",\"string\"]},{\"name\":\"CleanStatus\",\"doc\":\"Data:StaticEnum\",\"defaul" +
                "t\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"IndividualId\",\"doc\":\"ForeignKey:Entit" +
                "yId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Pronouns\",\"doc\":\"Data:Dyn" +
                "amicEnum\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"GenderIdentity\",\"doc" +
                "\":\"Data:DynamicEnum\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Level__c\"" +
                ",\"doc\":\"Data:DynamicEnum:00NDp00000BbvCj\",\"default\":null,\"type\":[\"null\",\"string\"" +
                "]},{\"name\":\"Languages__c\",\"doc\":\"Data:Text:00NDp00000BbvCi\",\"default\":null,\"type" +
                "\":[\"null\",\"string\"]},{\"name\":\"GUID__c\",\"doc\":\"Data:Text:00NDp000009RrFq\",\"defaul" +
                "t\":null,\"type\":[\"null\",\"string\"]}]}");
        /// <summary>
        /// Data:ComplexValueType
        /// </summary>
        private com.sforce.eventbus.ChangeEventHeader _ChangeEventHeader;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _AccountId;
        /// <summary>
        /// Data:Boolean
        /// </summary>
        private System.Nullable<System.Boolean> _IsPersonAccount;
        /// <summary>
        /// Data:PersonName
        /// </summary>
        private com.sforce.eventbus.PersonName _Name;
        /// <summary>
        /// Data:Address
        /// </summary>
        private com.sforce.eventbus.Address _OtherAddress;
        /// <summary>
        /// Data:Address
        /// </summary>
        private com.sforce.eventbus.Address _MailingAddress;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _Phone;
        /// <summary>
        /// Data:Fax
        /// </summary>
        private string _Fax;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _MobilePhone;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _HomePhone;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _OtherPhone;
        /// <summary>
        /// Data:Phone
        /// </summary>
        private string _AssistantPhone;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _ReportsToId;
        /// <summary>
        /// Data:Email
        /// </summary>
        private string _Email;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _Title;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _Department;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _AssistantName;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _LeadSource;
        /// <summary>
        /// Data:Birthday
        /// </summary>
        private System.Nullable<System.Int64> _Birthdate;
        /// <summary>
        /// Data:StringPlusClob
        /// </summary>
        private string _Description;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _OwnerId;
        /// <summary>
        /// Data:Boolean
        /// </summary>
        private System.Nullable<System.Boolean> _HasOptedOutOfEmail;
        /// <summary>
        /// Data:Boolean
        /// </summary>
        private System.Nullable<System.Boolean> _HasOptedOutOfFax;
        /// <summary>
        /// Data:Boolean
        /// </summary>
        private System.Nullable<System.Boolean> _DoNotCall;
        /// <summary>
        /// CreatedDate:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _CreatedDate;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _CreatedById;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _LastModifiedDate;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _LastModifiedById;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _LastCURequestDate;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _LastCUUpdateDate;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _EmailBouncedReason;
        /// <summary>
        /// Data:DateTime
        /// </summary>
        private System.Nullable<System.Int64> _EmailBouncedDate;
        /// <summary>
        /// Data:Text
        /// </summary>
        private string _Jigsaw;
        /// <summary>
        /// ExternalForeignKey:ExternalId
        /// </summary>
        private string _JigsawContactId;
        /// <summary>
        /// Data:StaticEnum
        /// </summary>
        private string _CleanStatus;
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        private string _IndividualId;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _Pronouns;
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        private string _GenderIdentity;
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCj
        /// </summary>
        private string _Level__c;
        /// <summary>
        /// Data:Text:00NDp00000BbvCi
        /// </summary>
        private string _Languages__c;
        /// <summary>
        /// Data:Text:00NDp000009RrFq
        /// </summary>
        private string _GUID__c;
        public virtual global::Avro.Schema Schema {
            get {
                return ContactChangeEvent._SCHEMA;
            }
        }
        /// <summary>
        /// Data:ComplexValueType
        /// </summary>
        public com.sforce.eventbus.ChangeEventHeader ChangeEventHeader {
            get {
                return this._ChangeEventHeader;
            }
            set {
                this._ChangeEventHeader = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string AccountId {
            get {
                return this._AccountId;
            }
            set {
                this._AccountId = value;
            }
        }
        /// <summary>
        /// Data:Boolean
        /// </summary>
        public System.Nullable<System.Boolean> IsPersonAccount {
            get {
                return this._IsPersonAccount;
            }
            set {
                this._IsPersonAccount = value;
            }
        }
        /// <summary>
        /// Data:PersonName
        /// </summary>
        public com.sforce.eventbus.PersonName Name {
            get {
                return this._Name;
            }
            set {
                this._Name = value;
            }
        }
        /// <summary>
        /// Data:Address
        /// </summary>
        public com.sforce.eventbus.Address OtherAddress {
            get {
                return this._OtherAddress;
            }
            set {
                this._OtherAddress = value;
            }
        }
        /// <summary>
        /// Data:Address
        /// </summary>
        public com.sforce.eventbus.Address MailingAddress {
            get {
                return this._MailingAddress;
            }
            set {
                this._MailingAddress = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string Phone {
            get {
                return this._Phone;
            }
            set {
                this._Phone = value;
            }
        }
        /// <summary>
        /// Data:Fax
        /// </summary>
        public string Fax {
            get {
                return this._Fax;
            }
            set {
                this._Fax = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string MobilePhone {
            get {
                return this._MobilePhone;
            }
            set {
                this._MobilePhone = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string HomePhone {
            get {
                return this._HomePhone;
            }
            set {
                this._HomePhone = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string OtherPhone {
            get {
                return this._OtherPhone;
            }
            set {
                this._OtherPhone = value;
            }
        }
        /// <summary>
        /// Data:Phone
        /// </summary>
        public string AssistantPhone {
            get {
                return this._AssistantPhone;
            }
            set {
                this._AssistantPhone = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string ReportsToId {
            get {
                return this._ReportsToId;
            }
            set {
                this._ReportsToId = value;
            }
        }
        /// <summary>
        /// Data:Email
        /// </summary>
        public string Email {
            get {
                return this._Email;
            }
            set {
                this._Email = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string Title {
            get {
                return this._Title;
            }
            set {
                this._Title = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string Department {
            get {
                return this._Department;
            }
            set {
                this._Department = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string AssistantName {
            get {
                return this._AssistantName;
            }
            set {
                this._AssistantName = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string LeadSource {
            get {
                return this._LeadSource;
            }
            set {
                this._LeadSource = value;
            }
        }
        /// <summary>
        /// Data:Birthday
        /// </summary>
        public System.Nullable<System.Int64> Birthdate {
            get {
                return this._Birthdate;
            }
            set {
                this._Birthdate = value;
            }
        }
        /// <summary>
        /// Data:StringPlusClob
        /// </summary>
        public string Description {
            get {
                return this._Description;
            }
            set {
                this._Description = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string OwnerId {
            get {
                return this._OwnerId;
            }
            set {
                this._OwnerId = value;
            }
        }
        /// <summary>
        /// Data:Boolean
        /// </summary>
        public System.Nullable<System.Boolean> HasOptedOutOfEmail {
            get {
                return this._HasOptedOutOfEmail;
            }
            set {
                this._HasOptedOutOfEmail = value;
            }
        }
        /// <summary>
        /// Data:Boolean
        /// </summary>
        public System.Nullable<System.Boolean> HasOptedOutOfFax {
            get {
                return this._HasOptedOutOfFax;
            }
            set {
                this._HasOptedOutOfFax = value;
            }
        }
        /// <summary>
        /// Data:Boolean
        /// </summary>
        public System.Nullable<System.Boolean> DoNotCall {
            get {
                return this._DoNotCall;
            }
            set {
                this._DoNotCall = value;
            }
        }
        /// <summary>
        /// CreatedDate:DateTime
        /// </summary>
        public System.Nullable<System.Int64> CreatedDate {
            get {
                return this._CreatedDate;
            }
            set {
                this._CreatedDate = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string CreatedById {
            get {
                return this._CreatedById;
            }
            set {
                this._CreatedById = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> LastModifiedDate {
            get {
                return this._LastModifiedDate;
            }
            set {
                this._LastModifiedDate = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string LastModifiedById {
            get {
                return this._LastModifiedById;
            }
            set {
                this._LastModifiedById = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> LastCURequestDate {
            get {
                return this._LastCURequestDate;
            }
            set {
                this._LastCURequestDate = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> LastCUUpdateDate {
            get {
                return this._LastCUUpdateDate;
            }
            set {
                this._LastCUUpdateDate = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string EmailBouncedReason {
            get {
                return this._EmailBouncedReason;
            }
            set {
                this._EmailBouncedReason = value;
            }
        }
        /// <summary>
        /// Data:DateTime
        /// </summary>
        public System.Nullable<System.Int64> EmailBouncedDate {
            get {
                return this._EmailBouncedDate;
            }
            set {
                this._EmailBouncedDate = value;
            }
        }
        /// <summary>
        /// Data:Text
        /// </summary>
        public string Jigsaw {
            get {
                return this._Jigsaw;
            }
            set {
                this._Jigsaw = value;
            }
        }
        /// <summary>
        /// ExternalForeignKey:ExternalId
        /// </summary>
        public string JigsawContactId {
            get {
                return this._JigsawContactId;
            }
            set {
                this._JigsawContactId = value;
            }
        }
        /// <summary>
        /// Data:StaticEnum
        /// </summary>
        public string CleanStatus {
            get {
                return this._CleanStatus;
            }
            set {
                this._CleanStatus = value;
            }
        }
        /// <summary>
        /// ForeignKey:EntityId
        /// </summary>
        public string IndividualId {
            get {
                return this._IndividualId;
            }
            set {
                this._IndividualId = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string Pronouns {
            get {
                return this._Pronouns;
            }
            set {
                this._Pronouns = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum
        /// </summary>
        public string GenderIdentity {
            get {
                return this._GenderIdentity;
            }
            set {
                this._GenderIdentity = value;
            }
        }
        /// <summary>
        /// Data:DynamicEnum:00NDp00000BbvCj
        /// </summary>
        public string Level__c {
            get {
                return this._Level__c;
            }
            set {
                this._Level__c = value;
            }
        }
        /// <summary>
        /// Data:Text:00NDp00000BbvCi
        /// </summary>
        public string Languages__c {
            get {
                return this._Languages__c;
            }
            set {
                this._Languages__c = value;
            }
        }
        /// <summary>
        /// Data:Text:00NDp000009RrFq
        /// </summary>
        public string GUID__c {
            get {
                return this._GUID__c;
            }
            set {
                this._GUID__c = value;
            }
        }
        public virtual object Get(int fieldPos) {
            switch (fieldPos) {
                case 0: return this.ChangeEventHeader;
                case 1: return this.AccountId;
                case 2: return this.IsPersonAccount;
                case 3: return this.Name;
                case 4: return this.OtherAddress;
                case 5: return this.MailingAddress;
                case 6: return this.Phone;
                case 7: return this.Fax;
                case 8: return this.MobilePhone;
                case 9: return this.HomePhone;
                case 10: return this.OtherPhone;
                case 11: return this.AssistantPhone;
                case 12: return this.ReportsToId;
                case 13: return this.Email;
                case 14: return this.Title;
                case 15: return this.Department;
                case 16: return this.AssistantName;
                case 17: return this.LeadSource;
                case 18: return this.Birthdate;
                case 19: return this.Description;
                case 20: return this.OwnerId;
                case 21: return this.HasOptedOutOfEmail;
                case 22: return this.HasOptedOutOfFax;
                case 23: return this.DoNotCall;
                case 24: return this.CreatedDate;
                case 25: return this.CreatedById;
                case 26: return this.LastModifiedDate;
                case 27: return this.LastModifiedById;
                case 28: return this.LastCURequestDate;
                case 29: return this.LastCUUpdateDate;
                case 30: return this.EmailBouncedReason;
                case 31: return this.EmailBouncedDate;
                case 32: return this.Jigsaw;
                case 33: return this.JigsawContactId;
                case 34: return this.CleanStatus;
                case 35: return this.IndividualId;
                case 36: return this.Pronouns;
                case 37: return this.GenderIdentity;
                case 38: return this.Level__c;
                case 39: return this.Languages__c;
                case 40: return this.GUID__c;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue) {
            switch (fieldPos) {
                case 0: this.ChangeEventHeader = (com.sforce.eventbus.ChangeEventHeader)fieldValue; break;
                case 1: this.AccountId = (System.String)fieldValue; break;
                case 2: this.IsPersonAccount = (System.Nullable<System.Boolean>)fieldValue; break;
                case 3: this.Name = (com.sforce.eventbus.PersonName)fieldValue; break;
                case 4: this.OtherAddress = (com.sforce.eventbus.Address)fieldValue; break;
                case 5: this.MailingAddress = (com.sforce.eventbus.Address)fieldValue; break;
                case 6: this.Phone = (System.String)fieldValue; break;
                case 7: this.Fax = (System.String)fieldValue; break;
                case 8: this.MobilePhone = (System.String)fieldValue; break;
                case 9: this.HomePhone = (System.String)fieldValue; break;
                case 10: this.OtherPhone = (System.String)fieldValue; break;
                case 11: this.AssistantPhone = (System.String)fieldValue; break;
                case 12: this.ReportsToId = (System.String)fieldValue; break;
                case 13: this.Email = (System.String)fieldValue; break;
                case 14: this.Title = (System.String)fieldValue; break;
                case 15: this.Department = (System.String)fieldValue; break;
                case 16: this.AssistantName = (System.String)fieldValue; break;
                case 17: this.LeadSource = (System.String)fieldValue; break;
                case 18: this.Birthdate = (System.Nullable<System.Int64>)fieldValue; break;
                case 19: this.Description = (System.String)fieldValue; break;
                case 20: this.OwnerId = (System.String)fieldValue; break;
                case 21: this.HasOptedOutOfEmail = (System.Nullable<System.Boolean>)fieldValue; break;
                case 22: this.HasOptedOutOfFax = (System.Nullable<System.Boolean>)fieldValue; break;
                case 23: this.DoNotCall = (System.Nullable<System.Boolean>)fieldValue; break;
                case 24: this.CreatedDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 25: this.CreatedById = (System.String)fieldValue; break;
                case 26: this.LastModifiedDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 27: this.LastModifiedById = (System.String)fieldValue; break;
                case 28: this.LastCURequestDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 29: this.LastCUUpdateDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 30: this.EmailBouncedReason = (System.String)fieldValue; break;
                case 31: this.EmailBouncedDate = (System.Nullable<System.Int64>)fieldValue; break;
                case 32: this.Jigsaw = (System.String)fieldValue; break;
                case 33: this.JigsawContactId = (System.String)fieldValue; break;
                case 34: this.CleanStatus = (System.String)fieldValue; break;
                case 35: this.IndividualId = (System.String)fieldValue; break;
                case 36: this.Pronouns = (System.String)fieldValue; break;
                case 37: this.GenderIdentity = (System.String)fieldValue; break;
                case 38: this.Level__c = (System.String)fieldValue; break;
                case 39: this.Languages__c = (System.String)fieldValue; break;
                case 40: this.GUID__c = (System.String)fieldValue; break;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
