// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.sforce.eventbus {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
    public partial class PersonName : global::Avro.Specific.ISpecificRecord {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PersonName"",""namespace"":""com.sforce.eventbus"",""fields"":[{""name"":""Salutation"",""default"":null,""type"":[""null"",""string""]},{""name"":""FirstName"",""default"":null,""type"":[""null"",""string""]},{""name"":""LastName"",""default"":null,""type"":[""null"",""string""]},{""name"":""MiddleName"",""default"":null,""type"":[""null"",""string""]},{""name"":""InformalName"",""default"":null,""type"":[""null"",""string""]},{""name"":""Suffix"",""default"":null,""type"":[""null"",""string""]}]}");
        private string _Salutation;
        private string _FirstName;
        private string _LastName;
        private string _MiddleName;
        private string _InformalName;
        private string _Suffix;
        public virtual global::Avro.Schema Schema {
            get {
                return PersonName._SCHEMA;
            }
        }
        public string Salutation {
            get {
                return this._Salutation;
            }
            set {
                this._Salutation = value;
            }
        }
        public string FirstName {
            get {
                return this._FirstName;
            }
            set {
                this._FirstName = value;
            }
        }
        public string LastName {
            get {
                return this._LastName;
            }
            set {
                this._LastName = value;
            }
        }
        public string MiddleName {
            get {
                return this._MiddleName;
            }
            set {
                this._MiddleName = value;
            }
        }
        public string InformalName {
            get {
                return this._InformalName;
            }
            set {
                this._InformalName = value;
            }
        }
        public string Suffix {
            get {
                return this._Suffix;
            }
            set {
                this._Suffix = value;
            }
        }
        public virtual object Get(int fieldPos) {
            switch (fieldPos) {
                case 0: return this.Salutation;
                case 1: return this.FirstName;
                case 2: return this.LastName;
                case 3: return this.MiddleName;
                case 4: return this.InformalName;
                case 5: return this.Suffix;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
        public virtual void Put(int fieldPos, object fieldValue) {
            switch (fieldPos) {
                case 0: this.Salutation = (System.String)fieldValue; break;
                case 1: this.FirstName = (System.String)fieldValue; break;
                case 2: this.LastName = (System.String)fieldValue; break;
                case 3: this.MiddleName = (System.String)fieldValue; break;
                case 4: this.InformalName = (System.String)fieldValue; break;
                case 5: this.Suffix = (System.String)fieldValue; break;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
