// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.sforce.eventbus
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Some_Custom_Object__ChangeEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Some_Custom_Object__ChangeEvent\",\"namespace\":\"com.sforce" +
				".eventbus\",\"fields\":[{\"name\":\"ChangeEventHeader\",\"doc\":\"Data:ComplexValueType\",\"" +
				"type\":{\"type\":\"record\",\"name\":\"ChangeEventHeader\",\"namespace\":\"com.sforce.eventb" +
				"us\",\"fields\":[{\"name\":\"entityName\",\"type\":\"string\"},{\"name\":\"recordIds\",\"type\":{" +
				"\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"changeType\",\"type\":{\"type\":\"enum\",\"na" +
				"me\":\"ChangeType\",\"namespace\":\"com.sforce.eventbus\",\"symbols\":[\"CREATE\",\"UPDATE\"," +
				"\"DELETE\",\"UNDELETE\",\"GAP_CREATE\",\"GAP_UPDATE\",\"GAP_DELETE\",\"GAP_UNDELETE\",\"GAP_O" +
				"VERFLOW\"]}},{\"name\":\"changeOrigin\",\"type\":\"string\"},{\"name\":\"transactionKey\",\"ty" +
				"pe\":\"string\"},{\"name\":\"sequenceNumber\",\"type\":\"int\"},{\"name\":\"commitTimestamp\",\"" +
				"type\":\"long\"},{\"name\":\"commitNumber\",\"type\":\"long\"},{\"name\":\"commitUser\",\"type\":" +
				"\"string\"},{\"name\":\"nulledFields\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"nam" +
				"e\":\"diffFields\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"changedFields" +
				"\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}},{\"name\":\"OwnerId\",\"doc\":\"ForeignK" +
				"ey:EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Name\",\"doc\":\"Data" +
				":Text\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"CreatedDate\",\"doc\":\"Cre" +
				"atedDate:DateTime\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"CreatedById\"," +
				"\"doc\":\"ForeignKey:EntityId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"La" +
				"stModifiedDate\",\"doc\":\"Data:DateTime\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"n" +
				"ame\":\"LastModifiedById\",\"doc\":\"ForeignKey:EntityId\",\"default\":null,\"type\":[\"null" +
				"\",\"string\"]},{\"name\":\"Custom_Checkobx__c\",\"doc\":\"Data:Boolean:00NDp000009Rr9i\",\"" +
				"default\":null,\"type\":[\"null\",\"boolean\"]},{\"name\":\"EZ_Money__c\",\"doc\":\"Data:Curre" +
				"ncy:00NDp000009RrEO\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Birthday_" +
				"_c\",\"doc\":\"Data:DateOnly:00NDp000009RrET\",\"default\":null,\"type\":[\"null\",\"long\"]}" +
				",{\"name\":\"Some_DateTime__c\",\"doc\":\"Data:DateTime:00NDp000009RrEY\",\"default\":null" +
				",\"type\":[\"null\",\"long\"]},{\"name\":\"Email_Wemail__c\",\"doc\":\"Data:Email:00NDp000009" +
				"RrEd\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"LocalDegrees__c\",\"doc\":\"" +
				"Data:Location:00NDp000009RrEi\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"n" +
				"ame\":\"Location\",\"namespace\":\"com.sforce.eventbus\",\"fields\":[{\"name\":\"Latitude\",\"" +
				"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Longitude\",\"default\":null,\"type" +
				"\":[\"null\",\"double\"]},{\"name\":\"XyzEncoded\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]}]}]},{\"name\":\"LocalDecimal__c\",\"doc\":\"Data:Location:00NDp000009RrEn\",\"default\"" +
				":null,\"type\":[\"null\",\"Location\"]},{\"name\":\"Numero__c\",\"doc\":\"Data:Double:00NDp00" +
				"0009RrEs\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"Percento__c\",\"doc\":\"" +
				"Data:Percent:00NDp000009RrEx\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"" +
				"TellyPhone__c\",\"doc\":\"Data:Phone:00NDp000009RrF2\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"PickleSingle__c\",\"doc\":\"Data:DynamicEnum:00NDp000009RrF7\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"PickleMulit__c\",\"doc\":\"Data:Mult" +
				"iEnum:00NDp000009RrFC\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Texty__" +
				"c\",\"doc\":\"Data:Text:00NDp000009RrFH\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
				"name\":\"Rich_Text__c\",\"doc\":\"Data:HtmlStringPlusClob:00NDp000009RrFM\",\"default\":n" +
				"ull,\"type\":[\"null\",\"string\"]},{\"name\":\"Encrypt__c\",\"doc\":\"Data:EncryptedText:00N" +
				"Dp000009RrFR\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"Timey__c\",\"doc\":" +
				"\"Data:TimeOnly:00NDp000009RrFW\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"" +
				"Linky__c\",\"doc\":\"Data:Url:00NDp000009RrFb\",\"default\":null,\"type\":[\"null\",\"string" +
				"\"]},{\"name\":\"GUID__c\",\"doc\":\"Data:Text:00NDp000009RrFg\",\"default\":null,\"type\":[\"" +
				"null\",\"string\"]}]}");
		/// <summary>
		/// Data:ComplexValueType
		/// </summary>
		private com.sforce.eventbus.ChangeEventHeader _ChangeEventHeader;
		/// <summary>
		/// ForeignKey:EntityId
		/// </summary>
		private string _OwnerId;
		/// <summary>
		/// Data:Text
		/// </summary>
		private string _Name;
		/// <summary>
		/// CreatedDate:DateTime
		/// </summary>
		private System.Nullable<System.Int64> _CreatedDate;
		/// <summary>
		/// ForeignKey:EntityId
		/// </summary>
		private string _CreatedById;
		/// <summary>
		/// Data:DateTime
		/// </summary>
		private System.Nullable<System.Int64> _LastModifiedDate;
		/// <summary>
		/// ForeignKey:EntityId
		/// </summary>
		private string _LastModifiedById;
		/// <summary>
		/// Data:Boolean:00NDp000009Rr9i
		/// </summary>
		private System.Nullable<System.Boolean> _Custom_Checkobx__c;
		/// <summary>
		/// Data:Currency:00NDp000009RrEO
		/// </summary>
		private System.Nullable<System.Double> _EZ_Money__c;
		/// <summary>
		/// Data:DateOnly:00NDp000009RrET
		/// </summary>
		private System.Nullable<System.Int64> _Birthday__c;
		/// <summary>
		/// Data:DateTime:00NDp000009RrEY
		/// </summary>
		private System.Nullable<System.Int64> _Some_DateTime__c;
		/// <summary>
		/// Data:Email:00NDp000009RrEd
		/// </summary>
		private string _Email_Wemail__c;
		/// <summary>
		/// Data:Location:00NDp000009RrEi
		/// </summary>
		private com.sforce.eventbus.Location _LocalDegrees__c;
		/// <summary>
		/// Data:Location:00NDp000009RrEn
		/// </summary>
		private com.sforce.eventbus.Location _LocalDecimal__c;
		/// <summary>
		/// Data:Double:00NDp000009RrEs
		/// </summary>
		private System.Nullable<System.Double> _Numero__c;
		/// <summary>
		/// Data:Percent:00NDp000009RrEx
		/// </summary>
		private System.Nullable<System.Double> _Percento__c;
		/// <summary>
		/// Data:Phone:00NDp000009RrF2
		/// </summary>
		private string _TellyPhone__c;
		/// <summary>
		/// Data:DynamicEnum:00NDp000009RrF7
		/// </summary>
		private string _PickleSingle__c;
		/// <summary>
		/// Data:MultiEnum:00NDp000009RrFC
		/// </summary>
		private string _PickleMulit__c;
		/// <summary>
		/// Data:Text:00NDp000009RrFH
		/// </summary>
		private string _Texty__c;
		/// <summary>
		/// Data:HtmlStringPlusClob:00NDp000009RrFM
		/// </summary>
		private string _Rich_Text__c;
		/// <summary>
		/// Data:EncryptedText:00NDp000009RrFR
		/// </summary>
		private string _Encrypt__c;
		/// <summary>
		/// Data:TimeOnly:00NDp000009RrFW
		/// </summary>
		private System.Nullable<System.Int64> _Timey__c;
		/// <summary>
		/// Data:Url:00NDp000009RrFb
		/// </summary>
		private string _Linky__c;
		/// <summary>
		/// Data:Text:00NDp000009RrFg
		/// </summary>
		private string _GUID__c;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Some_Custom_Object__ChangeEvent._SCHEMA;
			}
		}
		/// <summary>
		/// Data:ComplexValueType
		/// </summary>
		public com.sforce.eventbus.ChangeEventHeader ChangeEventHeader
		{
			get
			{
				return this._ChangeEventHeader;
			}
			set
			{
				this._ChangeEventHeader = value;
			}
		}
		/// <summary>
		/// ForeignKey:EntityId
		/// </summary>
		public string OwnerId
		{
			get
			{
				return this._OwnerId;
			}
			set
			{
				this._OwnerId = value;
			}
		}
		/// <summary>
		/// Data:Text
		/// </summary>
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		/// <summary>
		/// CreatedDate:DateTime
		/// </summary>
		public System.Nullable<System.Int64> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				this._CreatedDate = value;
			}
		}
		/// <summary>
		/// ForeignKey:EntityId
		/// </summary>
		public string CreatedById
		{
			get
			{
				return this._CreatedById;
			}
			set
			{
				this._CreatedById = value;
			}
		}
		/// <summary>
		/// Data:DateTime
		/// </summary>
		public System.Nullable<System.Int64> LastModifiedDate
		{
			get
			{
				return this._LastModifiedDate;
			}
			set
			{
				this._LastModifiedDate = value;
			}
		}
		/// <summary>
		/// ForeignKey:EntityId
		/// </summary>
		public string LastModifiedById
		{
			get
			{
				return this._LastModifiedById;
			}
			set
			{
				this._LastModifiedById = value;
			}
		}
		/// <summary>
		/// Data:Boolean:00NDp000009Rr9i
		/// </summary>
		public System.Nullable<System.Boolean> Custom_Checkobx__c
		{
			get
			{
				return this._Custom_Checkobx__c;
			}
			set
			{
				this._Custom_Checkobx__c = value;
			}
		}
		/// <summary>
		/// Data:Currency:00NDp000009RrEO
		/// </summary>
		public System.Nullable<System.Double> EZ_Money__c
		{
			get
			{
				return this._EZ_Money__c;
			}
			set
			{
				this._EZ_Money__c = value;
			}
		}
		/// <summary>
		/// Data:DateOnly:00NDp000009RrET
		/// </summary>
		public System.Nullable<System.Int64> Birthday__c
		{
			get
			{
				return this._Birthday__c;
			}
			set
			{
				this._Birthday__c = value;
			}
		}
		/// <summary>
		/// Data:DateTime:00NDp000009RrEY
		/// </summary>
		public System.Nullable<System.Int64> Some_DateTime__c
		{
			get
			{
				return this._Some_DateTime__c;
			}
			set
			{
				this._Some_DateTime__c = value;
			}
		}
		/// <summary>
		/// Data:Email:00NDp000009RrEd
		/// </summary>
		public string Email_Wemail__c
		{
			get
			{
				return this._Email_Wemail__c;
			}
			set
			{
				this._Email_Wemail__c = value;
			}
		}
		/// <summary>
		/// Data:Location:00NDp000009RrEi
		/// </summary>
		public com.sforce.eventbus.Location LocalDegrees__c
		{
			get
			{
				return this._LocalDegrees__c;
			}
			set
			{
				this._LocalDegrees__c = value;
			}
		}
		/// <summary>
		/// Data:Location:00NDp000009RrEn
		/// </summary>
		public com.sforce.eventbus.Location LocalDecimal__c
		{
			get
			{
				return this._LocalDecimal__c;
			}
			set
			{
				this._LocalDecimal__c = value;
			}
		}
		/// <summary>
		/// Data:Double:00NDp000009RrEs
		/// </summary>
		public System.Nullable<System.Double> Numero__c
		{
			get
			{
				return this._Numero__c;
			}
			set
			{
				this._Numero__c = value;
			}
		}
		/// <summary>
		/// Data:Percent:00NDp000009RrEx
		/// </summary>
		public System.Nullable<System.Double> Percento__c
		{
			get
			{
				return this._Percento__c;
			}
			set
			{
				this._Percento__c = value;
			}
		}
		/// <summary>
		/// Data:Phone:00NDp000009RrF2
		/// </summary>
		public string TellyPhone__c
		{
			get
			{
				return this._TellyPhone__c;
			}
			set
			{
				this._TellyPhone__c = value;
			}
		}
		/// <summary>
		/// Data:DynamicEnum:00NDp000009RrF7
		/// </summary>
		public string PickleSingle__c
		{
			get
			{
				return this._PickleSingle__c;
			}
			set
			{
				this._PickleSingle__c = value;
			}
		}
		/// <summary>
		/// Data:MultiEnum:00NDp000009RrFC
		/// </summary>
		public string PickleMulit__c
		{
			get
			{
				return this._PickleMulit__c;
			}
			set
			{
				this._PickleMulit__c = value;
			}
		}
		/// <summary>
		/// Data:Text:00NDp000009RrFH
		/// </summary>
		public string Texty__c
		{
			get
			{
				return this._Texty__c;
			}
			set
			{
				this._Texty__c = value;
			}
		}
		/// <summary>
		/// Data:HtmlStringPlusClob:00NDp000009RrFM
		/// </summary>
		public string Rich_Text__c
		{
			get
			{
				return this._Rich_Text__c;
			}
			set
			{
				this._Rich_Text__c = value;
			}
		}
		/// <summary>
		/// Data:EncryptedText:00NDp000009RrFR
		/// </summary>
		public string Encrypt__c
		{
			get
			{
				return this._Encrypt__c;
			}
			set
			{
				this._Encrypt__c = value;
			}
		}
		/// <summary>
		/// Data:TimeOnly:00NDp000009RrFW
		/// </summary>
		public System.Nullable<System.Int64> Timey__c
		{
			get
			{
				return this._Timey__c;
			}
			set
			{
				this._Timey__c = value;
			}
		}
		/// <summary>
		/// Data:Url:00NDp000009RrFb
		/// </summary>
		public string Linky__c
		{
			get
			{
				return this._Linky__c;
			}
			set
			{
				this._Linky__c = value;
			}
		}
		/// <summary>
		/// Data:Text:00NDp000009RrFg
		/// </summary>
		public string GUID__c
		{
			get
			{
				return this._GUID__c;
			}
			set
			{
				this._GUID__c = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ChangeEventHeader;
			case 1: return this.OwnerId;
			case 2: return this.Name;
			case 3: return this.CreatedDate;
			case 4: return this.CreatedById;
			case 5: return this.LastModifiedDate;
			case 6: return this.LastModifiedById;
			case 7: return this.Custom_Checkobx__c;
			case 8: return this.EZ_Money__c;
			case 9: return this.Birthday__c;
			case 10: return this.Some_DateTime__c;
			case 11: return this.Email_Wemail__c;
			case 12: return this.LocalDegrees__c;
			case 13: return this.LocalDecimal__c;
			case 14: return this.Numero__c;
			case 15: return this.Percento__c;
			case 16: return this.TellyPhone__c;
			case 17: return this.PickleSingle__c;
			case 18: return this.PickleMulit__c;
			case 19: return this.Texty__c;
			case 20: return this.Rich_Text__c;
			case 21: return this.Encrypt__c;
			case 22: return this.Timey__c;
			case 23: return this.Linky__c;
			case 24: return this.GUID__c;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ChangeEventHeader = (com.sforce.eventbus.ChangeEventHeader)fieldValue; break;
			case 1: this.OwnerId = (System.String)fieldValue; break;
			case 2: this.Name = (System.String)fieldValue; break;
			case 3: this.CreatedDate = (System.Nullable<System.Int64>)fieldValue; break;
			case 4: this.CreatedById = (System.String)fieldValue; break;
			case 5: this.LastModifiedDate = (System.Nullable<System.Int64>)fieldValue; break;
			case 6: this.LastModifiedById = (System.String)fieldValue; break;
			case 7: this.Custom_Checkobx__c = (System.Nullable<System.Boolean>)fieldValue; break;
			case 8: this.EZ_Money__c = (System.Nullable<System.Double>)fieldValue; break;
			case 9: this.Birthday__c = (System.Nullable<System.Int64>)fieldValue; break;
			case 10: this.Some_DateTime__c = (System.Nullable<System.Int64>)fieldValue; break;
			case 11: this.Email_Wemail__c = (System.String)fieldValue; break;
			case 12: this.LocalDegrees__c = (com.sforce.eventbus.Location)fieldValue; break;
			case 13: this.LocalDecimal__c = (com.sforce.eventbus.Location)fieldValue; break;
			case 14: this.Numero__c = (System.Nullable<System.Double>)fieldValue; break;
			case 15: this.Percento__c = (System.Nullable<System.Double>)fieldValue; break;
			case 16: this.TellyPhone__c = (System.String)fieldValue; break;
			case 17: this.PickleSingle__c = (System.String)fieldValue; break;
			case 18: this.PickleMulit__c = (System.String)fieldValue; break;
			case 19: this.Texty__c = (System.String)fieldValue; break;
			case 20: this.Rich_Text__c = (System.String)fieldValue; break;
			case 21: this.Encrypt__c = (System.String)fieldValue; break;
			case 22: this.Timey__c = (System.Nullable<System.Int64>)fieldValue; break;
			case 23: this.Linky__c = (System.String)fieldValue; break;
			case 24: this.GUID__c = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
